name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1.2']
        phpunit: [10.5.20]

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    services:
      mysql:
        image: mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, intl
          ini-values-csv: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          pecl: false

      - name: Check PHP Version
        run: php -v

      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist

      - name: Install PHPUnit
        run: composer global require "phpunit/phpunit=${{ matrix.phpunit }}"

      - name: Install WP Tests
        run: |
          if [ ! -f bin/install-wp-tests.sh ]; then
            mkdir -p bin
            curl -o bin/install-wp-tests.sh https://raw.githubusercontent.com/wp-cli/scaffold-command/master/templates/install-wp-tests.sh
            chmod +x bin/install-wp-tests.sh
          fi
          bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:33306 latest

      - name: Verify WP Tests Installation
        run: |
          ls -la /tmp/wordpress
          ls -la /tmp/wordpress-tests-lib
          cat /tmp/wordpress/wp-config.php

      - name: Create wp-tests-config.php
        run: |
          echo "<?php
          define( 'ABSPATH', dirname( __FILE__ ) . '/tmp/wordpress/' );
          define( 'DB_NAME', 'wordpress_test' );
          define( 'DB_USER', 'root' );
          define( 'DB_PASSWORD', 'root' );
          define( 'DB_HOST', '127.0.0.1:33306' );
          define( 'DB_CHARSET', 'utf8' );
          define( 'DB_COLLATE', '' );
          define( 'WP_TESTS_DOMAIN', 'example.org' );
          define( 'WP_TESTS_EMAIL', 'admin@example.org' );
          define( 'WP_TESTS_TITLE', 'Test Blog' );
          define( 'WP_PHP_BINARY', 'php' );
          define( 'WP_TESTS_DIR', dirname( __FILE__ ) . '/tmp/wordpress-tests-lib' );
          require_once WP_TESTS_DIR . '/includes/functions.php';
          require_once WP_TESTS_DIR . '/includes/bootstrap.php';
          " > wp-tests-config.php

      - name: Create bootstrap.php
        run: |
          echo "<?php
          require_once dirname( __DIR__ ) . '/vendor/autoload.php';
          require_once dirname( __DIR__ ) . '/wp-tests-config.php';
          require_once getenv('WP_PHPUNIT__DIR') . '/includes/bootstrap.php';
          " > tests/bootstrap.php

      - name: Debug MySQL Connection
        run: mysqladmin ping -h 127.0.0.1 -P 33306 --silent

      - name: PHPUnit tests
        run: vendor/bin/phpunit --bootstrap tests/bootstrap.php
